apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: lvvnga0qz-go
  janus-idp.io/tekton: lvvnga0qz-go
  backstage.io/kubernetes-id: lvvnga0qz-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lvvnga0qz-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
