apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: lvvnga0qz-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: lvvnga0qz-go 
  name: lvvnga0qz-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: lvvnga0qz-go 
